import { ArrowDown, Check, GitBranch, LockKeyhole, ShieldCheck, Timer, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import { AssetBadge, PageContainer } from "../components/outrun/components";
import { ASSETS, CATEGORY_LABEL, CATEGORIES } from "../lib/outrun/types";

const STEPS = [
  ["Choose a market", "Every OUTRUN market compares three assets over exactly one hour."],
  ["Pick your frontrunner", "Back the asset you think will have the highest percentage return."],
  ["One wallet, one pick", "Once you back an asset, that selection is locked. Add to it up to the 20 GEN maximum."],
  ["Highest return wins", "If every asset falls, the one that falls the least wins."],
  ["Settlement", "Bybit, Gate, and Bitget independently evaluate the window. A 2-of-3 agreement determines the result."],
  ["Claim", "Winners claim their share after resolution. Inconclusive markets follow the contract's refund rules."],
] as const;

export function HowItWorksPage() {
  return <PageContainer narrow><section className="surface how-hero"><div className="eyebrow"><GitBranch /> How OUTRUN works</div><h1>Three assets. One hour. Highest return wins.</h1><p className="lede">OUTRUN is a GenLayer-powered prediction market for relative performance. Pick the market that leads the pack, then let the exact 1-hour window decide.</p><div className="how-grid">{STEPS.map(([title, copy], index) => <article className="how-step" key={title}><div className="step-number">{index + 1}</div><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="how-lower"><div className="surface flow-card"><div className="eyebrow"><Timer /> Settlement flow</div><div className="flow">{["Start", "1-hour race", "3 sources", "2-of-3 consensus", "Winner / claim"].map((label, index) => <div key={label} className={index === 4 ? "flow-node primary" : "flow-node"}>{label}{index < 4 && <ArrowDown className="flow-arrow" size={14} />}</div>)}</div></div><div className="surface rule-card"><div className="eyebrow"><ShieldCheck /> Rules at a glance</div><div className="rule-list"><div className="rule"><LockKeyhole /> <span>One wallet can back only one asset per market. Same-side top-ups are allowed up to 20 GEN cumulative.</span></div><div className="rule"><Trophy /> <span>The winner is always the numerically highest return — including when all three returns are negative.</span></div><div className="rule"><Check /> <span>Settlement uses Bybit, Gate, and Bitget. A 2-of-3 source agreement is required, with up to 4 hours after the race for retries.</span></div></div></div></section><section className="surface detail-card section-gap"><div className="card-heading"><div><h2>Eligible assets</h2><p>V1 has exactly three categories and nine assets.</p></div></div><div className="asset-list" style={{ marginTop: 18 }}>{CATEGORIES.map((category) => <div className="asset-line" key={category} style={{ "--share": "100%", "--asset-color": "var(--lime)" } as React.CSSProperties}><div className="asset-left"><span className="asset-ticker">{CATEGORY_LABEL[category]}</span><span className="asset-name">{ASSETS[category].join(" · ")}</span></div><span className="asset-share">3 assets</span></div>)}</div><div className="explain-box">IWM wins over SPY and QQQ at -0.20%, -0.40%, and -0.85% because -0.20% is the highest return. Least negative still leads the pack.</div></section><div style={{ display: "flex", justifyContent: "center", marginTop: 20 }}><Link className="button primary-btn" to="/markets">Browse markets</Link></div></PageContainer>;
}
